### ISSUE TITLE
Carthage Build App Store Submission Bug

### ISSUE THREAD

**Issue by cbh2000** [mamaral/Neon#41]
When I use Neon via Carthage in my app and upload it to iTunes Connect, I get the following email from Apple:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "Wispeo". To process your delivery, the following issues must be corrected:
> 
> Invalid Bundle - Do not submit apps with GCC-style coverage instrumentation enabled. Specifically, the following Xcode build settings should be disabled: Instrument Program Flow Generate Test Coverage Files
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

The email should have a comma between "Instrument Program Flow" and "Generate Test Coverage Files."

Can we just disable these build options? I'm not sure why they'd be needed in the first place.

**Comment by mamaral** [comment]
These were added in order to get code coverage reporting services working, which at the time of setting them up weren't working with Swift to begin with. If you'd like to open a PR I could get it merged for you ASAP - I just started a new job so my open source dev work will likely be taking a back seat for a bit.

**Comment by cbh2000** [comment]
Thanks!
